apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
      - name: web-api
        image: ccr.ccs.tencentyun.com/test_space_0/web_test:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: web-api-service
spec:
  selector:
    app: web-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
